N1 = float (input ("Enter the first number:"))
N2 = float (input ("Enter the second number:"))
Addition = int (N1 + N2)
Substraction = int (N1 - N2)
Multification = int (N1 * N2)
Division = (N1/N2)
print ( "Addition:", Addition)
print ("Substraction:", Substraction)
print ( "Multification:", Multification)
print ("Division:", Division)